config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("todo_list.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("todo/", include("todo_list.todo_app.urls", namespace="todo")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

todo_list/todo_app/urls.py
from django.urls import path

from todo_list.todo_app.views import (
    createtodoitem_view,
    createtodolist_view,
    itemdelete_view,
    list_ItemTodolists_view,
    list_todolists_view,
    listdelte_view,
    updatetodoitem_view,
)

# always metion the app name in the urls file
app_name = "todo_app"

urlpatterns = [
    path("", list_todolists_view, name="todolists_index"),
    path("list/<int:list_id>/", list_ItemTodolists_view, name="list"),
    path("list/<int:pk>/delete/", listdelte_view, name="list-delete"),
    # CRUD pattern for todolists
    path("list/add/", createtodolist_view, name="add_list"),
    path("list/<int:list_id>/item/add", createtodoitem_view, name="item-add"),
    path("list/<int:list_id>/item/<int:pk>", updatetodoitem_view, name="item-update"),
    path(
        "list/<int:list_id>/item/<int:pk>/delete", itemdelete_view, name="item-delete"
    ),
]

todo_list/users/urls.py
from django.urls import path

from todo_list.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

todo_list/todo_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


def one_week_hence():
    """
    Returns a date 1 week in the future.
    """
    return timezone.now() + timezone.timedelta(weeks=1)


class TodoList(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("todo_app:list", args=[self.id])

    def __str__(self) -> str:
        return self.title


class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(TodoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            "todo_app:item-update", args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self) -> str:
        return f"{self.title}: due ({self.due_date})"

    class Meta:
        ordering = ["due_date"]

todo_list/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Todo list.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

todo_list/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

todo_list/todo_app/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from todo_list.todo_app.models import ToDoItem, TodoList


class ListTodoLists(ListView):
    model = TodoList
    template_name = "todo_app/index.html"
    # context_object_name = "object_list"
    # paginate_by = 10
    # ordering = ["title"]
    # queryset = TodoList.objects.all()


list_todolists_view = ListTodoLists.as_view()


class ItemListView(ListView):
    model = ToDoItem
    template_name = "todo_app/item_list.html"

    # context_object_name = "object_list"
    # paginate_by = 10
    # ordering = ["-created_date"]
    # queryset = ToDoItem.objects.all()

    def get_queryset(self):
        return ToDoItem.objects.filter(todo_list_id=self.kwargs["list_id"])

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = TodoList.objects.get(id=self.kwargs["list_id"])
        return context


list_ItemTodolists_view = ItemListView.as_view()


class CreateTodoList(CreateView):
    model = TodoList
    fields = ["title"]

    # template_name = "todo_app/create_todo_list.html"

    # def get_success_url(self):
    #     return reverse("todo_app:list_todolists")

    def get_context_data(self):
        context = super().get_context_data()
        context["title"] = "Add a new list"
        return context


createtodolist_view = CreateTodoList.as_view()


class ListDelete(DeleteView):
    model = TodoList
    # You have to use reverse_lazy() instead of reverse(),
    # as the urls are not loaded when the file is imported.
    success_url = reverse_lazy("todo_app:todolists_index")


listdelte_view = ListDelete.as_view()


class CreateToDoItem(CreateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    # template_name = "todo_app/create_todo_item.html"
    def get_initial(self):
        initial_data = super().get_initial()
        todo_list = TodoList.objects.get(id=self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super().get_context_data()
        todo_list = TodoList.objects.get(id=self.kwargs["list_id"])
        context["todo_list"] = todo_list
        context["title"] = "Create a new item"
        return context

    def get_success_url(self):
        return reverse("todo_app:list", args=[self.object.todo_list.id])


createtodoitem_view = CreateToDoItem.as_view()


class UpdateToDoItem(UpdateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    # template_name = "todo_app/create_todo_item.html"

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = self.object.todo_list
        context["title"] = "Update item"
        return context

    def get_success_url(self):
        return reverse("list", args=[self.object.todo_list.id])


updatetodoitem_view = UpdateToDoItem.as_view()


class ItemDelete(DeleteView):
    model = ToDoItem

    def get_success_url(self):
        return reverse_lazy("todo:list", args=[self.kwargs["list_id"]])

    def get_context_data(self, **kwarg):
        context = super().get_context_data(**kwarg)
        context["todo_list"] = self.object.todo_list
        return context


itemdelete_view = ItemDelete.as_view()

todo_list/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

todo_list/templates/todo_app/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Todo list{% endblock %}

{% block content %}

  <!--index.html-->

  {% if object_list %}

    <h3>All my lists</h3>

  {% endif %}

  <ul>

    {% for todolist in object_list %}

      <li>

        <div

          role="button"

          onclick="location.href='{% url "todo_app:list" todolist.id %}'">

          {{ todolist.title }}

        </div>

      </li>

    {% empty %}

      <h4>You have no lists!</h4>

    {% endfor %}

  </ul>
  <input
    value="Add a new list"
    type="button"
    onclick="location.href='{% url "todo_app:add_list" %}'"/>

{% endblock %}

todo_list/templates/todo_app/item_list.html
{% extends "base.html" %}


{% block content %}

  <div>

    <div>

      <div>

        <h3>Edit list:</h3>

        <h5>{{ todo_list.title | upper }}</h5>

      </div>

      <ul>

        {% for todo in object_list %}

          <li>

            <div>

              <div

                role="button"

                onclick="location.href='{% url "todo_app:item-update" todo_list.id todo.id %}'">

                {{ todo.title }}

                (Due {{ todo.due_date | date:"l, F j" }})

              </div>

            </div>

          </li>

        {% empty %}

          <p>There are no to-do items in this list.</p>

        {% endfor %}

      </ul>

      <p>

        <input

          value="Add a new item"

          type="button"

          onclick="location.href='{% url "todo_app:item-add" todo_list.id %}'"/>
        <input
          value="Delete this list"
          type="button"
          onclick="location.href=
            '{% url "todo_app:list-delete" todo_list.id %}'"/>


      </p>

    </div>

  </div>

{% endblock %}

todo_list/templates/todo_app/todoitem_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h3>Delete To-do Item</h3>

  <p>Are you sure you want to delete the item: <b>{{ object.title }}</b>
    from the list <i>{{ todo_list.title }}</i>?</p>

  <form method="POST">
    {% csrf_token %}
    <input
      value="Yes, delete."
      type="submit">
    <input
      value="Cancel"
      type="button"
      onclick="location.href='{% url "todo_app:list" todo_list.id %}';">
  </form>

{% endblock %}

todo_list/templates/todo_app/todoitem_form.html
{% extends "base.html" %}


{% block content %}


  <h3>{{ title }}</h3>

  <form method="post">

    {% csrf_token %}

    <table>

      {{ form.as_table }}

    </table>

    <input

      value="Submit"

      type="submit">

    <input

      value="Cancel"

      type="button"

      onclick="location.href='{% url "todo_app:list" todo_list.id %}'">
    {% if object %}
      <input
        value="Delete this item"
        type="button"
        onclick="location.href=
          '{% url "todo_app:item-delete" todo_list.id object.id %}'">
    {% endif %}


  </form>


{% endblock %}

todo_list/templates/todo_app/todolist_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <!--todolist_confirm_delete.html-->

  <h3>Delete List</h3>

  <p>Are you sure you want to delete the list <i>{{ object.title }}</i>?</p>

  <form method="POST">
    {% csrf_token %}
    <input
      value="Yes, delete."
      type="submit">
  </form>
  <input
    value="Cancel"
    type="button"
    onclick="location.href='{% url "todo_app:todolists_index" %}';">

{% endblock %}

todo_list/templates/todo_app/todolist_form.html
<!-- todo_list/todo_app/templates/todo_app/todolist_form.html -->

{% extends "base.html" %}


{% block content %}


<h3>{{ title }}</h3>

<div>

    <div>

        <form method="post">

            {% csrf_token %}

            {{ form.as_p }}

            <input

                value="Save"

                type="submit">

            <input

                value="Cancel"

                type="button"

                onclick="location.href='{% url "todo_app:todolists_index" %}';">

        </form>

    </div>

</div>


{% endblock %}